version: '3.8'

services:
  mongodb:
    image: 'mongo:8.2.2'
    container_name: itix-mongo
    restart: unless-stopped
    hostname: 'localhost'
    ports:
      - "27017:27017"
    volumes:
      - 'mongo_data:/data/db'
    environment:
      - "MONGO_INITDB_DATABASE=smart-itinerary-planner"
  redis:
    image: 'redis:8.4.0'
    container_name: itix-redis
    restart: unless-stopped
    hostname: 'localhost'
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

volumes:
  mongo_data:
  redis_data: