spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
    redis:
      url: ${REDIS_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

management:
  endpoint:
    env:
      keys-to-sanitize: password, apiKey, secretKey, email

logging:
  level:
    com:
      codrshi:
        smart_itinerary_planner: INFO
    org:
      springframework:
        security: INFO
        web: INFO
        boot: INFO
        data: INFO
        ai: INFO
        aop:
          interceptor:
            AsyncExecutionInterceptor: DEBUG
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) %highlight([%thread]) %highlight(%-5level) %green(%logger{36}) %magenta([%X{X-Trace-Id}]) - %msg%n"

itinerary:
  async:
    corePoolSize: 5
    maxPoolSize: 15
    queueCapacity: 100
    timeLimitScheduler:
      corePoolSize: 4

security:
  require-ssl: true