management:
  endpoint:
    env:
      keys-to-sanitize: password, apiKey, secretKey, email

logging:
  level:
    com:
      codrshi:
        smart_itinerary_planner: ${LOGGING_LEVEL:INFO}
    org:
      springframework:
        security: INFO
        web: INFO
        boot: INFO
        data: INFO
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) %highlight([%thread]) %highlight(%-5level) %green(%logger{36}) %magenta([%X{X-Trace-Id}]) - %msg%n"

security:
  require-ssl: true